# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Angular Indonesia
email: angular-indonesia@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Komunitas Pengguna Angular Indonesia
baseurl: "/blogs" # the subpath of your site, e.g. /blog
url: "https://angular-indonesia.github.io" # the base hostname & protocol for your site, e.g. http://example.com
excerpt_separator: <a name='more'></a>
paginate: 5
twitter_username: angular-indonesia
github_username:  angular-indonesia
disqus:
   shortname: 
google_analytics: 

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-paginate
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock

# SASS setup  
sass:
  sass_dir: _sass
  style: compressed
